import argparse
import json
from pathlib import Path

def compile_schema(schema_path: str, output_path: str):

    path = Path(schema_path)

    if not path.exists():
        raise FileNotFoundError(f"File Schema not found: {schema_path}")

    schema_data = json.loads(path.read_text())
    event_name = schema_data.get("event_name", "Network Event")
    fields = schema_data.get("fields", [])

    total_bytes = 0
    pack_lines = []
    unpack_lines = []

    for field in fields:
    name = field["name"]
    ftype = field["type"]

    if ftype == "u8":
      pack_lines.append(f"    buffer.writeu8(buf, {total_bytes}, {name})")
      unpack_lines.append(f"        {name} = buffer.readu8(buf, {total_bytes}),")
      total_bytes += 1
    elif ftype == "u16":
      pack_lines.append(f"    buffer.writeu16(buf, {total_bytes}, {name})")
      unpack_lines.append(f"        {name} = buffer.readu16(buf, {total_bytes}),")
      total_bytes += 2
    elif ftype == "bool":
      # Pack boolean into an 8-bit slot (1 or 0)
      pack_lines.append(
          f"    buffer.writeu8(buf, {total_bytes}, {name} and 1 or 0)"
      )
      unpack_lines.append(
          f"        {name} = buffer.readu8(buf, {total_bytes}) == 1,"
      )
      total_bytes += 1
    else:
      raise ValueError(f"Unsupported type '{ftype}' for field '{name}'")

  # 3. Construct the final Luau Module code template
  luau_code = f"""--!strict
-- [AUTO-GENERATED BY PACKETFORGE] - DO NOT EDIT MANUALLY

local {event_name} = {{}}
local buffer = buffer

function {event_name}.pack({', '.join([f"{f['name']}: {'number' if f['type'] != 'bool' else 'boolean'}" for f in fields])}): buffer
    local buf = buffer.create({total_bytes})
{'\n'.join(pack_lines)}
    return buf
end

function {event_name}.unpack(buf: buffer)
    return {{
{'\n'.join(unpack_lines)}
    }}
end

return {event_name}
"""

  # 4. Write output file
  out_path = Path(output_path)
  out_path.write_text(luau_code)
  print(
      f"Successfully compiled '{event_name}' into {output_path} (Allocated"
      f" {total_bytes} bytes)."
  )


if __name__ == "__main__":
  parser = argparse.ArgumentParser(
      description="PacketForge: Compile network schemas into optimized Luau"
      " buffers."
  )
  parser.add_argument(
      "--input",
      required=True,
      help="Path to the JSON schema configuration file",
  )
  parser.add_argument(
      "--output",
      required=True,
      help="Path where the generated Luau module will be saved",
  )

  args = parser.parse_args()
  compile_schema(args.input, args.output)